# Generated by Django 5.2.4 on 2026-05-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_api', '0003_userprofile_active_userprofile_emailid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='meetingdetail',
            name='follow_up_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='mom_api.meetingdetail'),
        ),
        migrations.AddField(
            model_name='meetingdetail',
            name='meeting_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=10),
        ),
        migrations.AlterField(
            model_name='meetingdetail',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='mom_api.projectdetail'),
        ),
        migrations.AddField(
            model_name='meetingdetail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='mom_api.client'),
        ),
    ]
