# Generated by Django 5.2.4 on 2026-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_api', '0004_client_meetingdetail_follow_up_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='is_archit_related',
            field=models.BooleanField(default=False),
        ),
    ]
