# Generated by Django 5.2.4 on 2026-06-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_api', '0005_projectdetail_is_archit_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='is_archit_related',
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='organization',
            field=models.CharField(default='iSyra', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(default='iSyra', max_length=50),
        ),
    ]
