# Generated by Django 5.2.4 on 2026-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_api', '0007_pushsubscription_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(unique=True),
        ),
    ]
