# Generated by Django 5.2.4 on 2026-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_api', '0008_alter_pushsubscription_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
