# Generated by Django 5.2.4 on 2026-06-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_api', '0009_reminder_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingdetail',
            name='notification_1h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingdetail',
            name='notification_24h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
