# Generated by Django 5.2.4 on 2026-06-09 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_api', '0010_meetingdetail_notification_1h_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('webhook', 'Google Apps Script Webhook'), ('service_account', 'Service Account')], default='webhook', max_length=20)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('spreadsheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sheet_name', models.CharField(blank=True, default='Meetings', max_length=100, null=True)),
                ('credentials_json', models.TextField(blank=True, help_text='Paste your Google Service Account JSON credentials here if using Service Account.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_status', models.CharField(blank=True, choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=20, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_sheet_integration', to='mom_api.projectdetail')),
            ],
        ),
    ]
